[package]
name = "ETH-script"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256k1 = { version = "0.24", features = ["rand"] }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
hex = "0.4.3"

